In [1]:
import rospy
import RobotControl_func_ros1 as RobotControl_func


[167.47319030761722, -612.0562744140625, 1.2398681640625, -3.1352149154112716, 0.05147079787466374, 0.8578558524396701]
這是用來測試有沒有被撞歪的座標

In [2]:
import rospy
import RobotControl_func_ros1 as RobotControl_func

rospy.init_node("RobotControl",anonymous=True)
robot = RobotControl_func.RobotControl_Func()
totallist=[]
[x,y,z,u,v,w] = robot.get_TMPos()
print([x,y,z,u,v,w])

$$$$$$$
(0.1674731903076172, -0.6120562744140625, 0.0012398681640625, -3.1352149154112716, 0.05147079787466374, 0.8578558524396701)
$$$$$$$
[167.47319030761722, -612.0562744140625, 1.2398681640625, -3.1352149154112716, 0.05147079787466374, 0.8578558524396701]


每次取得一個點位並寫入

In [19]:
robot.get_TMPos()
print(robot.get_TMPos())
totallist.append(robot.get_TMPos())
print(type(robot.get_TMPos()))


ROSInterruptException: rospy shutdown

In [95]:
print(len(totallist))
print(totallist) #顯示目前儲存的

20
[[594.0838069345818, -138.5408801148759, 467.4356994628906, -173.66317749023438, 1.6348413228988647, 40.24143981933594], [651.1750404833966, -137.92859227889605, 377.5372314453125, -161.86044311523438, 6.094341278076173, 43.08310317993164], [380.57412494766294, -154.7507657518352, 465.6792907714844, 155.37606811523438, 0.7027701139450073, 40.455318450927734], [552.544283046787, 91.85597185453206, 469.34497070312506, -178.34031677246094, 26.35577392578125, 79.72480773925783], [505.931211898094, 40.430569496767646, 417.74749755859375, -178.93786621093753, 24.97023963928223, 77.29475402832031], [379.65062208488035, -171.83297921094038, 396.77734375, 149.84552001953128, -2.5344710350036626, 37.02196502685547], [313.1101271400841, -216.13275617872853, 464.00189208984375, 165.38563537597656, -8.392745971679688, 7.755660057067872], [316.2141420548246, -218.0021395206294, 411.0020446777344, 164.49418640136716, -22.723831176757812, 1.4787429571151733], [233.0353363977323, -175.30989595431373

把點位寫入

In [94]:
file_name = 'EIH_PosSet.txt'
with open(file_name, 'w+') as file:
    for sublist in totallist:
        file.write(str(sublist))
        file.write('\n')

In [141]:
[x,y,z,u,v,w] = robot.get_TMPos()
print([x,y,z,u,v,w])

(0.4812396240234375, -0.08837464141845704, 0.5219412231445313, 3.021293139777061, -0.0004731992204881803, 0.8152398155181677)
(-5.605193857299268e-48, 5.605193857299268e-48, 5.605193857299268e-48, -9.782908802243343e-47, 9.782908802243343e-47, 9.782908802243343e-47)
[402.77810975455776, 277.7974932907167, 521.9412231445312, 173.1073455810547, -0.027112318202853203, 46.709800720214844]


In [145]:
robot.set_TMPos([594.0838069345818, -138.5408801148759, 467.4356994628906, -173.66317749023438, 1.6348413228988647, 40.24143981933594]
)       
#回正中間高度一定要大於100才不會撞到

[0.3221174926757813, -0.5180438842773437, 0.46743569946289065, -3.0309942366798928, 0.028533363832244956, 0.7023456205905642]
[INFO] [1706959269.428046]: point 1 (Tag 1) is reached


In [108]:
[x,y,z,u,v,w]=[100, 100, 100.4959716796875, -176.01728820800784, 0.5390524864196777, 46.80111312866211]
robot.set_TMPos([564.4543755213471, -172.14735558855622, 398.3766174316407, -167.48153686523438, -10.199124336242678, 27.746347427368164])#mm  | x+    <- y+   z+是往上
#一定要大於100才不會撞到
#robot.set_TMPos([484.1042532418399, -86.53510553787287, 396.6761474609375, -178.4583587646484, -0.2089095413684845, 44.86580276489258])
#z軸似乎比實際上少了3公分

[0.2774029541015625, -0.5208560791015625, 0.39837661743164066, -2.9231042545986026, -0.17800830048771593, 0.4842651180098327]
[INFO] [1706957149.165105]: point 1 (Tag 1) is reached


In [1]:
from gripper import Gripper

In [5]:
from gripper import Gripper
G = Gripper()
G.gripper_soft_off()


Response: b'091003e800030130'
Close gripper
Response: b'091003e800030130'


In [5]:
G.gripper_reset()

Activate gripper:
Clear: 09 10 03 E8 00 03 06 00 00 00 00 00 00 73 30
Response: b'091003e800030130'
Set: 09 10 03 E8 00 03 06 01 00 00 00 00 00 72 E1
b'D z@\xa0 \xcc'
b'\t\x03\x021\x00L\x15'
Activate Complete


In [4]:
G.gripper_on()

Open gripper
Response: b'091003e800030130'


In [138]:
G.gripper_soft_off()
#G.gripper_on()

Close gripper
Response: b'091003e800030130'


In [35]:
G.gripper_status()

NameError: name 'G' is not defined

In [1]:
import numpy as np

print(np.load('Camera2Gripper.npy')) #偏移矩陣

print(np.load('RC2G.npy')) #旋轉矩陣

print(np.load('INS.npy')) #內參矩陣


[[-9.99523694e-01  2.23258360e-02  2.13059047e-02  3.12689041e+01]
 [-2.32043880e-02 -9.98851480e-01 -4.19198950e-02 -8.59567950e+01]
 [ 2.03455377e-02 -4.23943188e-02  9.98893779e-01 -1.14847755e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.99888145 -0.04660927  0.00796429]
 [ 0.04537618  0.99223829  0.11577645]
 [-0.01329873 -0.11528555  0.99324337]]
[[606.77737141   0.         321.6328648 ]
 [  0.         606.70030442 236.95293668]
 [  0.           0.           1.        ]]


In [3]:
import numpy as np

def rotation_matrix_to_quaternion(R):
    trace = np.trace(R)
    if trace > 0:
        S = 0.5 / np.sqrt(trace + 1.0)
        w = 0.25 / S
        x = (R[2, 1] - R[1, 2]) * S
        y = (R[0, 2] - R[2, 0]) * S
        z = (R[1, 0] - R[0, 1]) * S
    elif R[0, 0] > R[1, 1] and R[0, 0] > R[2, 2]:
        S = 2.0 * np.sqrt(1.0 + R[0, 0] - R[1, 1] - R[2, 2])
        w = (R[2, 1] - R[1, 2]) / S
        x = 0.25 * S
        y = (R[0, 1] + R[1, 0]) / S
        z = (R[0, 2] + R[2, 0]) / S
    elif R[1, 1] > R[2, 2]:
        S = 2.0 * np.sqrt(1.0 + R[1, 1] - R[0, 0] - R[2, 2])
        w = (R[0, 2] - R[2, 0]) / S
        x = (R[0, 1] + R[1, 0]) / S
        y = 0.25 * S
        z = (R[1, 2] + R[2, 1]) / S
    else:
        S = 2.0 * np.sqrt(1.0 + R[2, 2] - R[0, 0] - R[1, 1])
        w = (R[1, 0] - R[0, 1]) / S
        x = (R[0, 2] + R[2, 0]) / S
        y = (R[1, 2] + R[2, 1]) / S
        z = 0.25 * S

    return np.array([w, x, y, z])

# 旋轉矩陣
rotation_matrix = np.array([[ 0.92574834, -0.31393438,  0.21079662],
       [ 0.10926284,  0.75575232,  0.64567799],
       [-0.36201055, -0.57470309,  0.73393782]])

# 轉換為四元數
quaternion = rotation_matrix_to_quaternion(rotation_matrix)

print("四元數：")
print(quaternion)

from scipy.spatial.transform import Rotation as R
r = R.from_matrix(rotation_matrix)
r.as_quat()
print("四元數：scipy")
print(quaternion)

四元數：
[ 0.92404525 -0.33017352  0.15497271  0.11449581]
四元數：scipy
[ 0.92404525 -0.33017352  0.15497271  0.11449581]


In [4]:
import numpy as np
from scipy.spatial.transform import Rotation as R

def quaternion_to_rotation_matrix(q):
    a, b, c, d = q
    R = np.array([[1 - 2*(c**2 + d**2), 2*(b*c - a*d), 2*(a*c + b*d)],
                  [2*(b*c + a*d), 1 - 2*(b**2 + d**2), 2*(c*d - a*b)],
                  [2*(b*d - a*c), 2*(a*b + c*d), 1 - 2*(b**2 + c**2)]])
    return R

# 四元數
quaternion = np.array([-0.679, 0.726, -0.074, -0.081])

# 轉換為旋轉矩陣
rotation_matrix = quaternion_to_rotation_matrix(quaternion)

print("旋轉矩陣：")
print(rotation_matrix)


r = R.from_quat(quaternion)
r.as_matrix()
print("旋轉矩陣：scipy")
print(rotation_matrix)

旋轉矩陣：
[[ 0.975926 -0.217446 -0.01712 ]
 [ 0.00255  -0.067274  0.997896]
 [-0.218104 -0.97392  -0.065104]]
旋轉矩陣：scipy
[[ 0.975926 -0.217446 -0.01712 ]
 [ 0.00255  -0.067274  0.997896]
 [-0.218104 -0.97392  -0.065104]]


In [5]:
def convert_coordinates(window_width, window_height, image_width, image_height, click_x, click_y):
    # 計算寬度和高度的比例因子
    width_scale = image_width / window_width
    height_scale = image_height / window_height
    
    # 將視窗中的點擊位置轉換為原始大小影像中的位置
    original_x = int(click_x * width_scale)
    original_y = int(click_y * height_scale)
    
    return original_x, original_y

# 視窗大小
window_width = 889
window_height = 500

# 原始影像大小
image_width = 640
image_height = 480

# 在視窗中的點擊位置
click_x = 300
click_y = 200

# 轉換為原始影像中的位置
original_x, original_y = convert_coordinates(window_width, window_height, image_width, image_height, click_x, click_y)

print("在原始影像中的位置：({}, {})".format(original_x, original_y))

在原始影像中的位置：(215, 192)


In [146]:
import pyrealsense2 as rs
pipeline = rs.pipeline()
#self.colorizer = rs.colorizer()
config = rs.config()
#self.config.enable_device('f0265339') #只有一隻相機就不用指定
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)
align_to = rs.stream.color
align = rs.align(align_to)
profile = pipeline.start(config)
depth_sensor = profile.get_device().first_depth_sensor()
depth_scale = depth_sensor.get_depth_scale()  
frames = pipeline.wait_for_frames()
aligned_frames = align.process(frames)
depth_frame = aligned_frames.get_depth_frame()
color_frame = aligned_frames.get_color_frame()
_intrin = depth_frame.profile.as_video_stream_profile().intrinsics
print(_intrin)
pipeline.stop()

[ 640x480  p[319.108 241.311]  f[611.058 611.026]  Inverse Brown Conrady [0 0 0 0 0] ]


In [147]:
import cv2
rvec=np.matrix([[-0.67507828],
                [ 0.3170204 ],
                [ 0.2399557 ]])

rmatx = 0
rmatx = cv2.Rodrigues(rvec,rmatx)[0]
r_mat2,_ = cv2.Rodrigues(rvec)
print(rmatx)
print(r_mat2)


NameError: name 'np' is not defined

[[ 9.97138831e-01  7.19587478e-02  2.31536055e-02 -4.18799845e+01]
 [-7.36243805e-02  9.93934636e-01  8.16908186e-02  1.76238195e+01]
 [-1.71348015e-02 -8.31617572e-02  9.96388740e-01  1.61677344e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]  目前的camera到gripper