In [1]:
import rospy
import RobotControl_func_ros1 as RobotControl_func


In [2]:
rospy.init_node("RobotControl",anonymous=True)
robot = RobotControl_func.RobotControl_Func()
totallist=[]

每次取得一個點位並寫入

In [7]:
robot.get_TMPos()
print(robot.get_TMPos())
totallist.append(robot.get_TMPos())
print(type(robot.get_TMPos()))


(0.24601629638671876, -0.4165542297363281, 0.43866174316406253, -3.121152625907326, 0.02034719987372109, 0.7940779380222346)
(-5.605193857299268e-48, 5.605193857299268e-48, -5.605193857299268e-48, 9.782908802243343e-47, 9.782908802243343e-47, 9.782908802243343e-47)
(0.24601629638671876, -0.4165542297363281, 0.43866174316406253, -3.121152625907326, 0.02034719987372109, 0.7940779380222346)
(-5.605193857299268e-48, 5.605193857299268e-48, -5.605193857299268e-48, 9.782908802243343e-47, 9.782908802243343e-47, 9.782908802243343e-47)
[468.5081120359449, -120.58852912104827, 438.66174316406256, -178.82887268066406, 1.16580867767334, 45.49731445312501]
(0.24601629638671876, -0.4165542297363281, 0.43866174316406253, -3.121152625907326, 0.02034719987372109, 0.7940779380222346)
(-5.605193857299268e-48, 5.605193857299268e-48, -5.605193857299268e-48, 9.782908802243343e-47, 9.782908802243343e-47, 9.782908802243343e-47)
(0.24601629638671876, -0.4165542297363281, 0.43866174316406253, -3.121152625907326,

In [5]:
print(len(totallist))
print(totallist) #顯示目前儲存的

0
[]


把點位寫入

In [4]:
file_name = 'EIH_PosSet.txt'
with open(file_name, 'a') as file:
    for sublist in totallist:
        for item in sublist:
            file.write(str(item) + ' ')
        file.write('\n')

In [3]:
[x,y,z,u,v,w] = robot.get_TMPos()
print([x,y,z,u,v,w])

(0.29731997680664063, -0.47174743652343754, 0.24122178649902346, -2.9738001891093506, 0.06501696259816259, 0.8044920963069349)
(4.313757978452796e-30, 2.7652330733746882e-30, 5.605193857299268e-48, -1.3502126877836258e-32, 4.050634862816383e-32, 9.250644754216073e-30)
[543.8127831552957, -123.33883959089049, 241.22178649902347, -170.38619995117188, 3.7251975536346436, 46.09400177001953]


In [4]:
robot.set_TMPos([481.2400478259802, -88.37447223143911, 521.943603515625, 173.10702514648438, -0.027281902730464935, 46.70990753173829])       
#回正中間高度一定要大於100才不會撞到

[0.27779791259765624, -0.40277828979492186, 0.521943603515625, 3.0212875471387717, -0.00047615902885544416, 0.8152416797309308]
[INFO] [1706945304.082655]: point 1 (Tag 1) is reached


In [16]:
[x,y,z,u,v,w]=[100, 100, 100.4959716796875, -176.01728820800784, 0.5390524864196777, 46.80111312866211]
robot.set_TMPos([564.4543755213471, -172.14735558855622, 398.3766174316407, -167.48153686523438, -10.199124336242678, 27.746347427368164])#mm  | x+    <- y+   z+是往上
#一定要大於100才不會撞到
#robot.set_TMPos([484.1042532418399, -86.53510553787287, 396.6761474609375, -178.4583587646484, -0.2089095413684845, 44.86580276489258])
#z軸似乎比實際上少了3公分

[0.2774029541015625, -0.5208560791015625, 0.39837661743164066, -2.9231042545986026, -0.17800830048771593, 0.4842651180098327]
[INFO] [1706861333.479234]: point 1 (Tag 1) is reached


In [3]:
from gripper import Gripper

In [4]:
G = Gripper()

Response: b'091003e800030130'


In [5]:
G.gripper_reset()

Activate gripper:
Clear: 09 10 03 E8 00 03 06 00 00 00 00 00 00 73 30
Response: b'091003e800030130'
Set: 09 10 03 E8 00 03 06 01 00 00 00 00 00 72 E1
b'D z@\xa0 \xcc'
b'\t\x03\x021\x00L\x15'
Activate Complete


In [9]:
G.gripper_on()

Open gripper
Response: b'091003e800030130'


In [10]:
G.gripper_soft_off()
#G.gripper_on()

Close gripper
Response: b'091003e800030130'


In [35]:
G.gripper_status()

NameError: name 'G' is not defined

In [22]:
import numpy as np

print(np.load('TC2G.npy')) #偏移矩陣

print(np.load('RC2G.npy')) #旋轉矩陣

print(np.load('INS.npy')) #內參矩陣


[[39.65148707]
 [-1.8229379 ]
 [29.29505309]]
[[ 0.99888145 -0.04660927  0.00796429]
 [ 0.04537618  0.99223829  0.11577645]
 [-0.01329873 -0.11528555  0.99324337]]
[[909.92766882   0.         640.45018871]
 [  0.         910.07773652 362.92579992]
 [  0.           0.           1.        ]]


In [3]:
import numpy as np

def rotation_matrix_to_quaternion(R):
    trace = np.trace(R)
    if trace > 0:
        S = 0.5 / np.sqrt(trace + 1.0)
        w = 0.25 / S
        x = (R[2, 1] - R[1, 2]) * S
        y = (R[0, 2] - R[2, 0]) * S
        z = (R[1, 0] - R[0, 1]) * S
    elif R[0, 0] > R[1, 1] and R[0, 0] > R[2, 2]:
        S = 2.0 * np.sqrt(1.0 + R[0, 0] - R[1, 1] - R[2, 2])
        w = (R[2, 1] - R[1, 2]) / S
        x = 0.25 * S
        y = (R[0, 1] + R[1, 0]) / S
        z = (R[0, 2] + R[2, 0]) / S
    elif R[1, 1] > R[2, 2]:
        S = 2.0 * np.sqrt(1.0 + R[1, 1] - R[0, 0] - R[2, 2])
        w = (R[0, 2] - R[2, 0]) / S
        x = (R[0, 1] + R[1, 0]) / S
        y = 0.25 * S
        z = (R[1, 2] + R[2, 1]) / S
    else:
        S = 2.0 * np.sqrt(1.0 + R[2, 2] - R[0, 0] - R[1, 1])
        w = (R[1, 0] - R[0, 1]) / S
        x = (R[0, 2] + R[2, 0]) / S
        y = (R[1, 2] + R[2, 1]) / S
        z = 0.25 * S

    return np.array([w, x, y, z])

# 旋轉矩陣
rotation_matrix = np.array([[ 0.92574834, -0.31393438,  0.21079662],
       [ 0.10926284,  0.75575232,  0.64567799],
       [-0.36201055, -0.57470309,  0.73393782]])

# 轉換為四元數
quaternion = rotation_matrix_to_quaternion(rotation_matrix)

print("四元數：")
print(quaternion)

from scipy.spatial.transform import Rotation as R
r = R.from_matrix(rotation_matrix)
r.as_quat()
print("四元數：scipy")
print(quaternion)

四元數：
[ 0.92404525 -0.33017352  0.15497271  0.11449581]
四元數：scipy
[ 0.92404525 -0.33017352  0.15497271  0.11449581]


In [4]:
import numpy as np
from scipy.spatial.transform import Rotation as R

def quaternion_to_rotation_matrix(q):
    a, b, c, d = q
    R = np.array([[1 - 2*(c**2 + d**2), 2*(b*c - a*d), 2*(a*c + b*d)],
                  [2*(b*c + a*d), 1 - 2*(b**2 + d**2), 2*(c*d - a*b)],
                  [2*(b*d - a*c), 2*(a*b + c*d), 1 - 2*(b**2 + c**2)]])
    return R

# 四元數
quaternion = np.array([-0.679, 0.726, -0.074, -0.081])

# 轉換為旋轉矩陣
rotation_matrix = quaternion_to_rotation_matrix(quaternion)

print("旋轉矩陣：")
print(rotation_matrix)


r = R.from_quat(quaternion)
r.as_matrix()
print("旋轉矩陣：scipy")
print(rotation_matrix)

旋轉矩陣：
[[ 0.975926 -0.217446 -0.01712 ]
 [ 0.00255  -0.067274  0.997896]
 [-0.218104 -0.97392  -0.065104]]
旋轉矩陣：scipy
[[ 0.975926 -0.217446 -0.01712 ]
 [ 0.00255  -0.067274  0.997896]
 [-0.218104 -0.97392  -0.065104]]


In [5]:
def convert_coordinates(window_width, window_height, image_width, image_height, click_x, click_y):
    # 計算寬度和高度的比例因子
    width_scale = image_width / window_width
    height_scale = image_height / window_height
    
    # 將視窗中的點擊位置轉換為原始大小影像中的位置
    original_x = int(click_x * width_scale)
    original_y = int(click_y * height_scale)
    
    return original_x, original_y

# 視窗大小
window_width = 889
window_height = 500

# 原始影像大小
image_width = 640
image_height = 480

# 在視窗中的點擊位置
click_x = 300
click_y = 200

# 轉換為原始影像中的位置
original_x, original_y = convert_coordinates(window_width, window_height, image_width, image_height, click_x, click_y)

print("在原始影像中的位置：({}, {})".format(original_x, original_y))

在原始影像中的位置：(215, 192)


In [7]:
import pyrealsense2 as rs
pipeline = rs.pipeline()
#self.colorizer = rs.colorizer()
config = rs.config()
#self.config.enable_device('f0265339') #只有一隻相機就不用指定
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)
align_to = rs.stream.color
align = rs.align(align_to)
profile = pipeline.start(config)
depth_sensor = profile.get_device().first_depth_sensor()
depth_scale = depth_sensor.get_depth_scale()  
frames = pipeline.wait_for_frames()
aligned_frames = align.process(frames)
depth_frame = aligned_frames.get_depth_frame()
color_frame = aligned_frames.get_color_frame()
_intrin = depth_frame.profile.as_video_stream_profile().intrinsics
print(_intrin)
pipeline.stop()

[ 640x480  p[319.108 241.311]  f[611.058 611.026]  Inverse Brown Conrady [0 0 0 0 0] ]


In [20]:
import cv2
rvec=np.matrix([[-0.67507828],
                [ 0.3170204 ],
                [ 0.2399557 ]])

rmatx = 0
rmatx = cv2.Rodrigues(rvec,rmatx)[0]
r_mat2,_ = cv2.Rodrigues(rvec)
print(rmatx)
print(r_mat2)


[[ 0.92492083 -0.31779432  0.2086342 ]
 [ 0.11450619  0.75620774  0.64423458]
 [-0.36250488 -0.57197607  0.7358217 ]]
[[ 0.92492083 -0.31779432  0.2086342 ]
 [ 0.11450619  0.75620774  0.64423458]
 [-0.36250488 -0.57197607  0.7358217 ]]


[[ 9.97138831e-01  7.19587478e-02  2.31536055e-02 -4.18799845e+01]
 [-7.36243805e-02  9.93934636e-01  8.16908186e-02  1.76238195e+01]
 [-1.71348015e-02 -8.31617572e-02  9.96388740e-01  1.61677344e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]  目前的camera到gripper